deployments:
  environmentMapping:
    development:
      - "development"
    testing:
      - "demo"
      - "[0-9][0-9][0-9]*"
      - "[0-9][0-9][0-9][0-9]*"
    staging:
      - "preproduction"
    production:
      - "production"
