name: "[Job] Plan/Deploy to Account"

on:
  workflow_call:
    inputs:
      workspace_name:
        description: "The terraform workspace to target for account actions"
        required: true
        type: string
      apply:
        description: "Whether to apply the deployment"
        required: false
        type: boolean
        default: false
    secrets:
      aws_access_key_id:
        description: "AWS Access Key ID"
        required: true
      aws_secret_access_key:
        description: "AWS Secret Access Key"
        required: true

jobs:
  terraform_account_workflow:
    runs-on: ubuntu-latest
    env:
      tf_dir: "./terraform/account"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: unfor19/install-aws-cli-action@v1
      - name: "Parse terraform version [directory: ${{ env.tf_dir }}]"
        id: tf_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v1.1.0
        with:
          terraform_directory: ${{ env.tf_dir }}
      - name: "Terraform version [${{ steps.tf_version.outputs.TERRAFORM_VERSION }}]"
        run: echo "terraform version [${{ steps.tf_version.outputs.TERRAFORM_VERSION }}]"
        working-directory: ${{ env.tf_dir }}
      - uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ steps.tf_version.outputs.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: OPGLpaStoreGithubAction

      - name: Lint Terraform
        run: terraform fmt -check -recursive
        working-directory: ${{ env.tf_dir }}
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.tf_dir }}

      - name: Terraform Plan
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
        run: |
          terraform workspace show
          terraform plan -lock-timeout=300s -input=false -parallelism=30 -out=terraform.plan
        working-directory: ${{ env.tf_dir }}

      - name: Terraform Apply
        if: inputs.apply == true
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
        run: |
          terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30 terraform.plan
        working-directory: ${{ env.tf_dir }}
