name: Pact Provider Verification

on:
  repository_dispatch:
    types: [provider-verification]
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Provider verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build up
      - run: go build -o ./api-test/tester ./api-test && chmod +x ./api-test/tester
      - run: cat ./docs/example-lpa.json | ./api-test/tester -jwtSecret=secret -expectedStatus=201 REQUEST PUT http://localhost:9000/lpas/M-3467-89QW-ERTY "`xargs -0`" && \
      - run: export JWT=$(./api-test/tester -jwtSecret=secret JWT)
      - name: Verify specified Pact
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          docker-compose run --rm pact-verifier \
            --header="X-Jwt-Authorization: Bearer $JWT" \
            --provider-version=$(git rev-parse HEAD) \
            --provider-branch=main \
            --publish \
            --user=admin \
            --password=${{ secrets.PACT_BROKER_PASSWORD }} \
            --url=${{ github.event.client_payload.pact_url }}
      - name: Verify pacts, including pending
        if: ${{ github.event_name == 'push' }}
        run: |
          docker-compose run --rm pact-verifier \
            --header="X-Jwt-Authorization: Bearer $JWT" \
            --provider-version=$(git rev-parse HEAD) \
            --provider-branch=main \
            --publish \
            --user=admin \
            --password=${{ secrets.PACT_BROKER_PASSWORD }} \
            --consumer-version-selectors='{"mainBranch": true}' \
            --enable-pending
      - name: Verify pacts are still upheld
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker-compose run --rm pact-verifier \
            --header="X-Jwt-Authorization=Bearer $JWT" \
            --provider-version=$(git rev-parse HEAD) \
            --provider-branch=${{ github.head_ref }} \
            --consumer-version-selectors='{"mainBranch": true}'
