name: "Security Analysis"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 16 * * 0"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Perform gosec analysis
        run: make gosec
