name: Main pipeline Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  generate-tag:
    name: Generate tag
    uses: ./.github/workflows/generate-tag.yml

  build:
    name: Build, Scan & Push Images
    needs: [generate-tag]
    uses: ./.github/workflows/build-push-images.yml
    with:
      docker_tag: ${{ needs.generate-tag.outputs.tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-dev-account:
    name: TF Deploy Dev Account
    uses: ./.github/workflows/account-deploy.yml
    with:
      workspace_name: development
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-dev-env:
    name: Deploy Development Environment
    needs: [build, generate-tag]
    uses: ./.github/workflows/env-deploy.yml
    with:
      workspace_name: development
      version_tag: ${{ needs.generate-tag.outputs.tag }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  test-dev-env:
    name: Test Development Environment
    needs: [deploy-dev-env]
    uses: ./.github/workflows/env-test.yml
    with:
      base_url: ${{ needs.deploy-dev-env.outputs.base_url }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
